Activity.create(:title => "50th Anniversary of Fred Trump’s Demolition of Steeplechase Pavilion", :date => "2016-08-01", :category => "art", :description => "The Coney Island History Projects first special exhibit of the 2016 season, opening on Memorial Day Weekend, will be The 50th Anniversary of Fred Trump’s Demolition of the Steeplechase Pavilion. A half century ago Coney’s most beautiful and imposing structure was demolished by developer Fred Trump, Donald Trumps father. This exhibit examines in photos, ephemera, and oral history, the importance of the pavilion and the memories of local personalities who dealt with Trump before and after the tragic demolition of a Coney Island landmark.")

Activity.create(:title => "Americana Monday at The Federal Bar", :date => "2016-08-01", :category => "food and drink", :description => "The best treatment for your Monday blues $15 8-piece bucket o’ chicken or $8 4-piece bucket o’chicken $3 off all american whiskeys $5 cast iron corn bread 1/2 price Gun Hill Gold pints")

Activity.create(:title => "Cakeshop Comedy", :date => "2016-08-02", :category => "comedy", :description => "FREE Comedy every Tuesday 8:30-10pm at Cake Shop NYC (152 Ludlow St, New York, NY 10002), brought to you by John Early, Liza Treyger, Jacqueline Novak & Naked Comedy Productions. Find out about weekly lineups, surprises and more! Facebook.com/CakeshopComedy Twitter.com/CakeshopComedy")

Activity.create(:title => "Brooklyn Literary Pub Crawl", :date => "2016-08-07", :category => "food and drink", :description => "Journey in the literary and cultural past of one of the world’s most famous boroughs. This tour will take you to several cool Brooklyn pubs closely connected to some of the literary greats of the neighborhood. Guides will tell you stories of the neighborhood, the writer’s who lived there, and perform some snippets of their work.")

Activity.create(:title => "Live at the Archway: Harlem Swing Dance Society", :date => "2016-08-11", :category => "dance", :description => "Live at The Archway is a Weekly Cabaret Below the Manhattan Bridge — with free performances, beer, wine, and a magical, only-in-DUMBO setting from June through September.")

Activity.create(:title => "Coney Island Is Still Dreamland at the Brooklyn Museum.", :date => "2016-08-21", :category => "Museum", :description => "Come and enjoy this site-specific installation by artist Stephen Powers who has been a longtime admirer of the fading craft of sign painting. Powers has revitalized the tradition of colorful, hand-painted signage and advertisements in an age of digitization. In his work, he uses logocategorys that have a superficially commercial look, combining them with his own text to create enigmatic meanings that deliver an emotional punch.")
